aws-samples/aws-service-catalog-reference-architectures

README.md, ci/taskcat-params-verify-all.json, ci/taskcat-params-verify-ec2vpc.json, codepipeline/install.sh, codepipeline/uninstall.sh, ec2/README.md, ec2/sc-portfolio-ec2.json, ec2/sc-portfolio-ec2VPC.json, emr/README.md, emr/sc-portfolio-emr.json, iam/README.md, rds/README.md, rds/sc-portfolio-rds.json, s3/README.md, s3/sc-portfolio-s3.json, templates/taskcat-verify-all.json, vpc/README.md, vpc/sc-portfolio-vpc.json
updated the portfolio stacks to include the enduser IAM group so it is no longer required as a separate step.  
Added regions and S3 url as variables to install script
updated the READMEs to reflect install changes
=> Update launch stacks

ec2/sc-ec2-linux-apache-simple.json, ec2/sc-ec2-linux-nginx-simple.json
updated security group and vpc in the webserver templates
=> updated webserver products for easier launch

ec2/sc-portfolio-ec2.json, iam/README.md, iam/SC-SNOW-demosetup.yml
added the snow demo template, added ec2 portfolio outputs to allow snow demo to add user to endusers group
=> added SNOW demo template

ci/buildspec-validate.yml, ci/sc-portfolio-ec2-defaults.json, ci/taskcat.yml, codepipeline/README.md, ec2/sc-ec2-linux-apache-nokey.json, ec2/sc-ec2-linux-nginx-nokey.json, ec2/sc-portfolio-ec2demo.json, ec2/sc-product-ec2-demowebserver.json, iam/README.md, iam/SC-ITSM-demosetup.yml
Added ITSM connector Demo templates
updated Security group linking to use group IDs for VPC with the webserver templates
updated the taskcat configs to allow reports viewable from S3
=> updated demo templates

ci/buildspec-validate.yml, ci/sc-portfolio-ec2-defaults.json, ci/taskcat.yml, codepipeline/README.md, ec2/sc-ec2-linux-apache-nokey.json, ec2/sc-ec2-linux-nginx-nokey.json, ec2/sc-portfolio-ec2.json, ec2/sc-portfolio-ec2demo.json, ec2/sc-product-ec2-demowebserver.json, iam/README.md, iam/SC-ITSM-demosetup.yml, iam/sc-ec2vpc-launchrole.yml, iam/sc-emr-launchrole.yml, iam/sc-enduser-iam.yml, iam/sc-rds-launchrole.yml, iam/sc-s3-launchrole.yml
updates for instructions to codepipeline
updated templates for ITSM demo setups
=> updated codepipeline instructions and templates

emr/sc-emr-ra.json, rds/sc-rds-mariadb-ra.json, rds/sc-rds-mssql-ra.json, rds/sc-rds-mysql-ra.json, rds/sc-rds-postgresql-ra.json
updated rds password to include underscore. updated password descriptions
updated emr instance types due to new EMR version compatibility
=> updates to RDS password regex and EMR instances types

emr/sc-emr-ra.json, emr/sc-product-emr.json
Added new EMR version 5.23
fixed missing EC2 keypair - keypair param is now added to the EMR cluster instances
=> updates to EMR template

labs/xacct-pipeline/README.md
=> Changed launch stack path

ec2/sc-product-ec2-demowebserver.json, ec2/sc-tagoptions.json
=> added sample tag options to demowebserver

codepipeline/sc-codepipeline-ra.json, ec2/sc-product-ec2-demowebserver.json, ec2/sc-tagoptions.json
removed temp buckets from the pipeline output
updated the tagoptions for the webserver demo
=> update pipeline and EC2 tagoptions

rds/sc-rds-mariadb-ra.json, rds/sc-rds-mssql-ra.json, rds/sc-rds-mysql-ra.json, rds/sc-rds-postgresql-ra.json
added m5 instance types
fixed password regex
added new database version ids
combined subnets into list selector
updated param descriptions to be more clear
=> updated RDS template db versions, instances, password regex

codepipeline/sc-codepipeline-ra.json, ec2/sc-ec2-linux-apache-nokey.json, ec2/sc-ec2-linux-apache-simple.json, ec2/sc-ec2-linux-nginx-nokey.json, ec2/sc-ec2-linux-nginx-simple.json, ec2/sc-ec2-linux-ra.json, ec2/sc-ec2-windows-ra.json, ec2/sc-product-ec2-webserver.json, iam/sc-enduser-iam.yml, vpc/sc-vpc-ra.json
updated the security policies in enduser and codepipeline.
added descriptions and scoped resources to templates.
=> Security policy updates

codepipeline/README.md, codepipeline/sc-codepipeline-ra.json, ecs/container-codepipeline-ra.json
additional instructions for spoke account ChildAccountAccess parameter.
cleaned up the ECS pipeline template in line with changes made in codepipeline.
=> updates to codepipeline README, updates to ECS codepipeline

codepipeline/README.md, serverless/sc-provision-serverless.yml, serverless/sc-serverless-lambda.yml
synced the serverless templates.
updated instructions for codepipeline for #44
=> serverless update, README update

ecs/fargate-private-vpc.yml, ecs/fargate-task.json, ecs/sc-product-fargatetask.json, iam/sc-ecs-launchrole.yml
fixed some IAM issues. 
param passing to task def product
added log group and portmapping to task def.
=> updates to ECS section

ecs/fargate-task.json
mappings for container sizes in task definition
=> added container size options to fargate task

product_template_mapping.tsx.txt
=> update template names

ec2/sc-ec2-windows-ra.json, iam/sc-ec2vpc-launchrole.yml, iam/sc-redshift-launchrole.yml, sagemaker/sc-sagemaker.yml, serverless/sc-provision-serverless.yml, serverless/sc-serverless-lambda.yml
updated versions for lambda runtimes:
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
formatting changes
=> runtime updates

codepipeline/buildspec.yml
Fix for : Missing  _"--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"_ in _update-stack-set_ in _buildspec.yaml_ resulting in codepipeline update failures.
=> IAM Capabilites fix to prevent Update process failure

codepipeline/ct_install_multi.sh
=> formatting

ecs/fargate-private-vpc.yml, ecs/fargate-service.json, ecs/sc-portfolio-ecs.json, ecs/sc-product-fargateservice.json
simplified the ECS product launch. 
added a complete load balanced service product
=> update to Fargate/ECS section: added service product

README.md, ecs/README.md, ecs/container-codepipeline-ra.json, ecs/fargate-service.json, ecs/sc-portfolio-ecs.json
Readme updates
added source info for ECS templates
added update ecs service permissions to ECS codepipeline
=> updates to README, source info, ECS update permission

ecs/codepipeline/buildspec-deploy.yml, ecs/container-codepipeline-ra.json, product_template_mapping.tsx.txt
updates to mappings
add additional info to ECS template meta data
update sample buildspec to use buildnumbers
=> updates for ECS

ec2/sc-ec2-linux-ra.json, ec2/sc-ec2-windows-ra.json, ecs/fargate-private-vpc.yml, ecs/fargate-service.json, ecs/fargate-task.json, emr/sc-emr-SparkHbase.json, emr/sc-emr-ra.json, rds/sc-rds-mariadb-ra.json, rds/sc-rds-mssql-ra.json, rds/sc-rds-mysql-ra.json, vpc/sc-vpc-ra.json
=> security updates

codepipeline/README.md, ecs/README.md, emr/sc-emr-ra.json
bug fix: conditional in the outputs for EMR template
minor README changes
=> fix conditional, README updates

security/guardduty/deploy_guardduty.yml, security/sc-portfolio-gd.json
=> added tracking id

sagemaker/README.md, sagemaker/emr-backed-notebook-instance.yaml, sagemaker/emr-backed-notebook-instance.yml, sagemaker/sc-portfolio-sagemaker.json, sagemaker/sc-product-sagemaker.json
Adding a new product template that stands up an EMR cluster, a notebook instance and connects the two. Most of the EMR cluster code has been reused from the EMR reference architecture from this repo.
=> New SageMaker notebook instance+EMR cluster template

conformance_packs/sc_AWSControlTowerDetectiveGuardrails.yaml, conformance_packs/sc_OperationalBestPracticesForAWSIdentityAndAccessManagement.yaml, conformance_packs/sc_OperationalBestPracticesForAmazonDynamoDB.yaml, conformance_packs/sc_OperationalBestPracticesForPCI-DSS.yaml, conformance_packs/sc_conformancepacks_prerequisites.yml
*Description of changes: For SC GSL existing conformance packs, adding the fdp numbers to the product templates.  
=> v101220 SC GSL Conformance Pack

rds/sc-portfolio-rds.json, rds/sc-product-rds-aurora.json, rds/sc-rds-aurora-ra.json
*Description of changes:* Added support for creating Aurora DB service catalog item
=> Added support for Aurora DB 

backup/backup-tagoptions.yml
Adding SC GSL Backup and TagOptions template.
=> v111220 SC GSL RA backup-tagoptions.yml

redshift/redshift-cluster-vpc.yml, redshift/redshift-commands.yml
Redshift CFN Templates - redshift-cluster-vpc.yml and redshift-commands.yml added in new directory redshift
=> Local update branch

blog_content/securing-third-party-data-and-ml-apps/README.md, blog_content/securing-third-party-data-and-ml-apps/admin-setup-app.yaml, blog_content/securing-third-party-data-and-ml-apps/adx.yaml, blog_content/securing-third-party-data-and-ml-apps/application.yaml, blog_content/securing-third-party-data-and-ml-apps/mlmodel.yaml, blog_content/securing-third-party-data-and-ml-apps/network.yaml, blog_content/securing-third-party-data-and-ml-apps/notebook.yaml, blog_content/securing-third-party-data-and-ml-apps/portfolio.yaml, blog_content/securing-third-party-data-and-ml-apps/s3_iam_kms.yaml
Releasing sample source code for a workshop.
These templates have been open source and guardian approved.
=> uploading CFN templates for reinvent workshop

blog_content/securing-third-party-data-and-ml-apps/admin-setup-app.yaml, blog_content/securing-third-party-data-and-ml-apps/adx.yaml, blog_content/securing-third-party-data-and-ml-apps/mlmodel.yaml, blog_content/securing-third-party-data-and-ml-apps/network.yaml, blog_content/securing-third-party-data-and-ml-apps/portfolio.yaml, blog_content/securing-third-party-data-and-ml-apps/s3_iam_kms.yaml
N/A
Adding recent changes and updates from September for CFNs.
=> Updated to latest CFN templates for release

blog_content/securing-third-party-data-and-ml-apps/portfolio.yaml
*Issue #, if available:
N/A
*Description of changes:
Update to CFN for release
=> Update S3 root URL

blog_content/securing-third-party-data-and-ml-apps/mlmodel.yaml, product_template_mapping.tsx.txt
*Issue #, if available:* Added three templates that show how to deploy ml models in a locked down VPC
*Description of changes:* Added three templates that show how to deploy ml models in a locked down VPC
=> Added three more templates
